### ISSUE TITLE
Allow/Support Chain Prefixes in CSV

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/safe-airdrop#337] opened 2022-01-13 09:47 UTC
Based on the v2 release review (https://github.com/gnosis/safe-apps-list/issues/92#issuecomment-1011916061) we got this feature request.

> I think it would be neat to either allow chain prefixes on the CSV file or ignore them when performing a drain. 
> As when doing so with an address with chain prefix it automatically populates the CSV with it, making it invalid:

Follow link for images.

**Comment by schmanu** [comment] 2022-01-13 09:59
This is a duplicate of #322

**Closed by schmanu** 2022-01-13 09:59 UTC
